### ISSUE TITLE
aioredis is archived

### ISSUE THREAD

**Issue by scabala** [performancemedia/eventiq#37]
Hi!

First of all, I would like to thank you for all your work on `eventiq` - it is a great framework. And despite it being very young, I decided to take it very seriously and try to build something with it.

As described in [aioredis](https://github.com/aio-libs/aioredis/) README, it is deprecated and in general, users should migrate to `redis.asyncio`. I've been hit by this, trying to use `RedisBroker` on Python 3.11 - cannot import it.

I do not know if you are aware of this - just wanted to give you heads up.

This begs the question - are brokers included inside this project meant as ready-to-use brokers or as a mere example how to build ones? Obviously, I can work around this issue by creating my own broker implementation but if `RedisBroker` is meant to be usable - I can try to craft a PR to fix it.

**Comment by RaRhAeu** [comment]
Hi,
thanks for your interest in project.
All brokers implementations should be ready-to-use (they may serve as an example too), however I had no time/reason to test/verify that all of them are working properly. Some of them are just 'drafts' to be tested/fixed/implemented if needed. The most stable one is `nats/JetStreamBroker` and I highly recommend using it. All PRs are welcome too! This time I fixed the issue with outdated/broken redis dependency [here](https://github.com/performancemedia/eventiq/pull/38), try upgrading eventiq version to 0.1.24.
Here is an example with redis broker: https://github.com/performancemedia/eventiq/blob/main/examples/web.py that worked fine for me. If you face any issues, please let me know. Would also love to hear some feedback about the framework in general.

**Comment by scabala** [comment]
Thank you for updating the project! With that I'll let myself to close the issue.

I've been able to use `eventiq` to do pretty much everything I wanted it too. Typing here is really, really nice, compared to other projects I've used (`celery`, `dramatiq`). Only issue I came up with is documentation - it could be broader but I was I able to find everything in source - i.e. how to use `ConsumerGroup`.
